[package]
authors = ["Jakub Pastuszek <jpastuszek@gmail.com>"]
build = "build.rs"
name = "varnishslog"
version = "0.1.0"

[[bench]]
harness = false
name = "stream_buf"

[[bench]]
harness = false
name = "access_log"

[build-dependencies]
serde_codegen = "0.8.4"

[dependencies]
assert_matches = "1.0.1"
bitflags = "0.7.0"
boolinator = "0.1.0"
chrono = "0.2.25"
clap = "2.10.0"
env_logger = "0.3.4"
linked-hash-map = "0.3.0"
log = "0.3.6"
nom = "1.2.4"
quick-error = "1.1.0"
serde = "0.8.4"
serde_json = "0.8.1"
stderrlog = "0.2.1"

[dev-dependencies]
bencher = "0.1.1"
