[package]
authors = ["Jakub Pastuszek <jpastuszek@gmail.com>"]
name = "varnishsyslogger"
version = "0.1.0"

[dependencies]
clap = "2.10.0"
log = "0.3.6"
nom = "1.2.4"
quick-error = "1.1.0"
stderrlog = "0.2.1"
