[package]
authors = ["Jakub Pastuszek <jpastuszek@gmail.com>"]
name = "varnishsyslogger"
version = "0.1.0"

[dependencies]
assert_matches = "1.0.1"
bitflags = "0.7.0"
clap = "2.10.0"
env_logger = "0.3.4"
log = "0.3.6"
nom = "1.2.4"
quick-error = "1.1.0"
stderrlog = "0.2.1"
